# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class ToolMetadata:
    name: str
    description: str
    semantic_description: str
    request_tag: str
    request_schema: str
    response_schema: str
    input_json_schema: str

@dataclass
class ToolResult:
    success: bool
    payload: str


class WitWorld(Protocol):

    @abstractmethod
    def get_metadata(self, source: str) -> ToolMetadata:
        """
        Load a Python tool's source and extract its metadata.
        """
        raise NotImplementedError

    @abstractmethod
    def handle(self, source: str, request_xml: str) -> ToolResult:
        """
        Execute a Python tool: load source, call handle(request_xml).
        """
        raise NotImplementedError

